### ISSUE TITLE
[Submission] Golem JS Preview Program

### ISSUE THREAD

**Issue by OjusWiZard** [golemfactory/golem-js-preview-program#3]
# Golem JS Preview Program Submission by @OjusWiZard

Thank you for your Golem JS Preview Program Submission!

Please make sure the feedback form in a Markdown file is filled for each of the tasks you’d like to submit!
Also, please make sure you've read the terms and conditions for this competition available here - 

## Legal Info

In order to receive the award, we need a minimum info about you for legal reasons:

- Email: ojuswimail@gmail.com
- Country of origin: India

## Preferred reward currency

There are two currencies you can receive a reward in - USD and GLM. Since GLM is our cryptocurrency, we provide an additional **10% bonus to all rewards paid in GLMs!**.

Choose the preferred currency by checking (with `x`) one of the boxes below:

- [x] USD
- [ ] GLM (+10% bonus)

Please note that if you already have an accepted assignment from any of the freelance websites (e.g. fiverr.com, freelancer.com, upwork.com), you need to choose a reward in USD.

## Repository link

https://github.com/OjusWiZard/golem-js-preview-program

## Submitted Tasks

Please check (with `x`) the boxes below with the tasks you'd like to submit:

- [x] Text2Speech
- [ ] Code Sandbox
- [ ] Parallel File Conversion
- [ ] Text2Speech Server
- [ ] Best Provider Selection

## How did you find out about Golem JS Preview Program? Please check (with `x`) the correct box below:

- [ ] fiverr.com 
- [ ] freelancer.com
- [x] upwork.com
- [ ] Digital Campaign (e.g. Reddit)
- [ ] Golem Network profiles
- [ ] Message on LinkedIn
- [ ] Other: [please answer here]

## How was your experience with Golem JS Preview Program so far?

I like exploring new technologies, and this was no different. I got to learn about the Golem network and many development tools and libraries around it that were fun working with.

## Were the tasks easy to understand and did you enjoy solving them?

The tasks were understandable and I liked to solve these challenges. Their difficulty is right on point, not too tough to understand, and not too easy to solve.

## How was your experience with a new Golem JS API?

The API needs a little more documentation in the handbook. I saw only one example covered using JS API and the reference section was also less informative. But, the SDK itself was easy to work with and seems decently robust.

## Do you have any general feedback about Golem? Is there something we could improve from your perspective?

The first question that came to my mind is how it maintains the accuracy of computation done on the Provider side. [This old Reddit post](https://www.reddit.com/r/GolemProject/comments/6p2d0y/computational_verifiability_in_golem/) was able to help but I would like to find out if there are any more updates.

## And that's it - thank you for your submission!

Our team will review and evaluate your feedback, then reward you with GLM reward for your future projects!

**Comment by VanDavv** [comment]
Hi @OjusWiZard,

Thank you very much for your submission. I've reviewed it and I'm happy to accept it! I gave your code a try and it worked well, the only thing I could potentially find missing is the lack of CLI arguments handling - to run the task like `npm run tts "hello world"` - but it's something additional and rather a nice-to-have.

Regarding the feedback itself, it's exactly what we were looking for. You provided great detail on the issues you've faced, solutions you've found and potential improvements we could add - excellent work!

I think the confusion with the documentation occurred due to our ongoing migration to the new docs. JS API got its section migrated and is available here - https://docs.golem.network/creators/javascript
The docs you've mentioned in your feedback are still referencing the old API, which, as you've noticed, is vastly different. 

Together with a note to remove the NodeJS sections from old docs and add a banner to point to new docs, I've analysed the rest of your feedback and added more of the action items to be made from our side. 

Thank you for taking part in this competition and kudos for great results!

**Comment by OjusWiZard** [comment]
Oh, I get it now.
Thanks for the info :)

**Comment by VanDavv** [comment]
Hey @OjusWiZard ,

We just released a new version of the `gvmkit-build`, `0.2.9`, available here - https://pypi.org/project/gvmkit-build/
It should contain the fix for the `chunked` issue.

Thanks again for your submission!

**Comment by OjusWiZard** [comment]
That's great! I'm glad to help :)
